import uscMin from "@/assets/icons/usc.webp";
import usc from "@/assets/icons/usc.webp";
import codoxoMin from "@/assets/icons/codoxo.webp";
import codoxo from "@/assets/icons/codoxo.webp";
import recoMin from "@/assets/icons/reco.webp";
import reco from "@/assets/icons/reco.webp";
import teradata from "@/assets/icons/teradata.webp";
import teradataMin from "@/assets/icons/teradata.webp";
import NexWeb from "@/assets/icons/NexWEB.webp";
import NexWebMin from "@/assets/icons/NexWEB.webp";

const details = {
  name: {
    first: "Brett",
    last: "Smith",
    nickname: "DZRootStack",
  },
  title: "Senior Software Engineer",
  biography: "Results-driven Senior Software Engineer with 11+ years of full-stack development experience across diverse industries, including finance, healthcare, e-commerce, and technology. Highly proficient in a wide range of languages and frameworks such as JavaScript, TypeScript, Python, PHP, Java, React, Angular, Vue.js, Node.js, Django, Spring Boot, and more. Adept in cloud infrastructure (AWS, Azure, GCP), DevOps, microservices, and database architecture. Proven ability to lead cross-functional teams, architect scalable applications, and implement secure, high-performance solutions tailored to business needs.",
  education: [
    {
      school: "University of Southern California",
      url: "https://usc.edu/",
      icon: usc,
      iconMin: uscMin,
      location: "Los Angeles, CA",
      degree: "Bachelor’s Degree in Computer Science",
      major: "Computer Science and Applied Mathematics",
      start: "Sep 2012",
      end: "May 2016",
    },
  ],
  experience: [
    {
      company: "NexWEB",
      url: "https://www.nexweb.com/",
      icon: NexWeb,
      iconMin: NexWebMin,
      location: "New York, NY",
      contract: "Contract",
      position: "Senior Software Engineer",
      start: "May 2022",
      end: "Present",
      description: [
        "Led development of scalable web applications using React, Next.js, Node.js, and TypeScript.",
        "Built microservices with Express, deployed across AWS, Azure, and GCP.",
        "Integrated APIs (GraphQL & REST) for seamless front-backend communication using Angular and Vue.js.",
        "Orchestrated CI/CD pipelines via Jenkins, Docker, and Kubernetes.",
        "Enhanced UI/UX using Svelte and optimized frontend performance (HTML5, CSS3).",
        "Managed complex state using Redux and Context API.",
        "Developed real-time features with Kafka and RabbitMQ.",
        "Applied security protocols (OAuth, JWT, HTTPS), ensuring robust data protection.",
        "Automated data pipelines with Python; improved efficiency and scalability.",
        "Promoted DevOps practices using Terraform and Prometheus for infrastructure-as-code and monitoring.",
        "Collaborated with cross-functional teams to ensure technical excellence and client satisfaction.",
        "Engineered and deployed a robust NFT marketplace infrastructure leveraging Solidity, Ethereum, and Polygon blockchains, integrating OpenZeppelin for smart contract development.",
        "Led the creation of dynamic smart contracts using Truffle, Hardhat, and Alchemy service, ensuring seamless deployment across Ethereum and Polygon networks.",
      ],
      skills: [
        "React",
        "Next.js",
        "Node.js",
        "TypeScript",
        "Python",
        "Jenkins",
        "AWS",
        "Azure",
        "GCP",
        "GraphQL",
        "NFT",
        "Solidity",
        "OpenZeppelin",
      ],
    },
    {
      company: "Reco Universal LLC",
      url: "https://www.recouniversal.com/",
      icon: reco,
      iconMin: recoMin,
      location: "New York, NY",
      contract: "Full-time",
      position: "Senior Full-Stack Developer",
      start: "June 2019",
      end: "April 2022",
      description: [
        "Built high-performance web apps with Laravel, React, Vue.js, and Angular.",
        "Modernized legacy systems using cutting-edge JavaScript frameworks.",
        "Developed backend systems with Django, Flask, and Node.js for large-scale data processing.",
        "Leveraged AWS (EC2, S3, RDS) for cloud deployments.",
        "Streamlined DevOps workflows with Docker, Kubernetes, and Elastic Beanstalk.",
        "Integrated third-party services via REST and GraphQL.",
        "Implemented robust testing (Jest, Mocha, Cypress) for quality assurance.",
        "Developed analytics features using Python, Pandas, and NumPy.",
        "Led Agile teams using Scrum practices; mentored junior engineers and fostered team growth.",
      ],
      skills: [
        "React",
        "Laravel",
        "Vue",
        "Angular",
        "Django",
        "Flask",
        "Docker",
        "Elastic BeanStalk",
        "Jest",
        "Mocha",
        "Cypress",
      ],
    },
    {
      company: "Codoxo",
      url: "https://www.codoxo.com/",
      icon: codoxo,
      iconMin: codoxoMin,
      location: "Atlanta, GA",
      contract: "Full-time",
      position: "Full Stack Developer",
      start: "Dec 2017",
      end: "May 2019",
      description: [
        "Developed and maintained full-stack solutions with Angular, Java, and Python.",
        "Built scalable backend APIs and data pipelines using MySQL, Redis, and Flask.",
        "Deployed apps to Microsoft Azure; used Azure DevOps for CI/CD automation.",
        "Adopted serverless computing (Azure Functions) for scalability.",
        "Integrated secure communication protocols (SSL/TLS); enhanced application performance via caching and CDN.",
        "Collaborated on accessibility-focused UI/UX and conducted code reviews and sprint planning.",
        "Integrated Azure Cognitive Services for smart features and real-time interactivity with AJAX.",
      ],
      skills: [
        "Angular",
        "Java",
        "Python",
        "Flask",
        "Redis",
        "Azure",
        "Azure Cognitive",
      ],
    },
    {
      company: "Teradata",
      url: "https://www.teradata.com/",
      icon: teradata,
      iconMin: teradataMin,
      location: "San Diego, CA",
      contract: "Full-time",
      position: "Full Stack Developer",
      start: "May 2014",
      end: "Nov 2017",
      description: [
        "Developed enterprise applications using Java, Spring Boot, Angular, and React.",
        "Modernized legacy systems with HTML5, CSS3, and modern JS frameworks.",
        "Built RESTful APIs and microservices; managed deployments on AWS and Azure.",
        "Utilized Jenkins and Git for CI/CD and version control.",
        "Architected SQL and NoSQL solutions with MySQL and MongoDB.",
        "Secured applications with OAuth2, JWT; adopted Agile and TDD methodologies.",
        "Delivered real-time dashboards using D3.js and React for data visualization.",
      ],
      skills: [
        "React",
        "Angular",
        "Java",
        "Node JS",
        "DevOps",
        "AWS",
        "Azure",
        "OAuth2",
        "JWT",
        "Material UI",
        "D3.js",
        "Data Visualization",
      ],
    },
  ],
  languages: [
    {
      name: "English",
      level: "C1",
    },
   
  ],
  contact: {
    location: "Florida, United States",
    email: "brett.smith.mi@outlook.com",
    phone: "+1 (773) 599 2010",
    website: "https://dzrootstack.vercel.app/",
    linkedin: "www.linkedin.com/in/brett-smith-8a9138351",
    github: "https://www.github.com/dzrootstack",
    researchgate: "https://www.researchgate.net/profile/dzrootstack",
    gitlab: "https://www.gitlab.com/dzrootstack",
    deviantart: "https://www.deviantart.com/dzrootstack",
  },
};

export default details;
